# Use postgres/example user/password credentials
version: '3.9'

env_file: ./docker.env

services:

  db:
    image: postgres:16.2-alpine3.19
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 256mb
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
