@startchen Climate Monitoring Database
entity CoordinateMonitoraggio {
    GeoID
    Name
    CountryCode
    Latitude
    Longitude
}

entity ParametriClimatici {
    Center
    Area
    Date
    Operator
    Wind
    Humidity
    Pressure
    Temperature
    Precipitation
    GlaciersAltitude
    GlaciersMass
}

entity OperatoriRegistrati {
    UserID
    Name
    Surname 
    CF
    Email 
    Password 
    Center
}

entity CentriMonitoraggio {
    CenterID
    Name
    Address
    Areas
}



relationship AssociatedWith {
}

relationship WorksIn{
}

relationship Provides{
}

AssociatedWith -(0,N)- CoordinateMonitoraggio
AssociatedWith -(1,N)- CentriMonitoraggio
WorksIn -(1,N)- CentriMonitoraggio
WorksIn -(1,1)- OperatoriRegistrati
Provides -(1,1)- ParametriClimatici
Provides -(0,N)- OperatoriRegistrati

@endchen